sudo: false
cache: 
  bundler: true
  directories:
    - protractor/node_modules
language: ruby
rvm:
  - 2.2.2
node_js:
  - "0.12"
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "node -v"
  - "cd protractor"
  - "npm install"
  - "cd testapp"
  - "npm start"
  - "sleep 5" # wait for angular test server to start
script:
  - bundle exec thor spec
notifications:
  email:
    on_success: never
    on_failure: never
