language: node_js
node_js:
  - stable
sudo: false
cache: 
  bundler: true
  directories:
    - protractor/node_modules
before_install: 
  - rvm install 2.2.2
  - rvm --default use 2.2.2
  - gem update --remote bundler
install:
  - bundle install --retry=3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "ruby -v"
  - "node -v"
  - "cd protractor"
  - "npm install"
  - "cd testapp"
  - "npm start"
  - "sleep 5" # wait for angular test server to start
script:
  - bundle exec thor spec
notifications:
  email:
    on_success: never
    on_failure: never
